### ISSUE TITLE
npm install fails at React template

### ISSUE THREAD

**Issue by rjkngs** [happeo/custom-widget-templates#12]
npm install fails with dependency errors:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@universe%2ffrontend-utils - Not found
npm ERR! 404 
npm ERR! 404  '@universe/frontend-utils@^0.35.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@happeouikit/content-renderer'
```

Same problem exists with package `@happeouikit/copy-to-clipboard-button`

**Comment by ankero** [comment]
Hi @TR-Livion, it seems that our email-notifications are not set since we didn't get notified from your message... 6 months ago. I apologies about that.

The dependency problem is now fixed by removing @happeouikit/copy-to-clipboard-button and @happeouikit/content-renderer. We are checking if we need to expose these through the WidgetSDK or if we can move the functions used from the internal package to the @happeouikit.

**Comment by lopezvit** [comment]
@ankero I would like to re-open this issue! I was having the same (similar) problem when trying to install content-renderer with `npm i -D @happeouikit/content-renderer`. I got this error:
```
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

```
And, when checking the logs, it complains about the package `@universe/frontend-utils@^0.35.1`
